### ISSUE TITLE
Norminette  3.2.95 does not start after installation

### ISSUE THREAD

**Issue by tjohnna** [42School/norminette#148]
First startup of norminette causes a "ModuleNotFoundError", the same error pops out after norm installation to a new virtual environment on the same machine.
![Norm 2021-05-15](https://user-images.githubusercontent.com/84227316/118356268-c8dee880-b58d-11eb-8871-50bb2a4a7223.jpg)

$ norminette --version
Traceback (most recent call last):
  File "C:\Curs21\Python39\Scripts\norminette-script.py", line 33, in <module>
    sys.exit(load_entry_point('norminette==3.2.95', 'console_scripts', 'norminette')())
  File "C:\Curs21\Python39\Scripts\norminette-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Curs21\Python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Curs21\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Curs21\Python39\lib\site-packages\norminette\__main__.py", line 8, in <module>
    from norminette.registry import Registry
  File "C:\Curs21\Python39\lib\site-packages\norminette\registry.py", line 3, in <module>
    import norminette.rules as rules
  File "C:\Curs21\Python39\lib\site-packages\norminette\rules\__init__.py", line 18, in <module>
    module = importlib.import_module("norminette.rules." + mod_name)
  File "C:\Curs21\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'norminette.rules.C:\\Curs21\\Python39\\Lib\\site-packages\\norminette\\rules\\check_assignation'

**Additional infos**
 - OS: Win10 20H2
 - python --version: 3.9.5
 - norminette -v: 3.2.95

**Additional context**
all required files and folders are in place;
proper read/write permissions to these folders are applied, it shouldn't be a problem with access rights, global environment paths in Windows are set.

**Comment by tjohnna** [comment]
replacement file _init_.py found
