### ISSUE TITLE
attribute + struct crashes norminette

### ISSUE THREAD

**Issue by antikostya** [42School/norminette#252]
**Describe the bug**
If after function split by __attribute__(()) goes struct in header file - norminette crashes

**Erroneous code**
```c
int	func(int arg) __attribute__((warn_unused_result))
		__attribute__((__nothrow__));

typedef struct s_struct
{
	int	smth;
}	t_struct;
```
`norminette -dd header.h` return:
```html
.NORME_ERRORS.h - IsFuncDeclaration In "GlobalScope" from "None" line 1":
		<INT> <TAB> <IDENTIFIER=func> <LPARENTHESIS> <INT> <SPACE> <IDENTIFIER=arg> <RPARENTHESIS> <SPACE> <IDENTIFIER=__attribute__> <LPARENTHESIS> <LPARENTHESIS> <IDENTIFIER=warn_unused_result> <RPARENTHESIS> <RPARENTHESIS> <NEWLINE>
		<TAB> <TAB> 
.NORME_ERRORS.h - IsFunctionCall In "Function" from "GlobalScope" line 2":
		<IDENTIFIER=__attribute__> <LPARENTHESIS> <LPARENTHESIS> <IDENTIFIER=__nothrow__> <RPARENTHESIS> <RPARENTHESIS> <SEMI_COLON> <NEWLINE>
.NORME_ERRORS.h - IsEmptyLine In "Function" from "GlobalScope" line 3":
		<NEWLINE>
.NORME_ERRORS.h - IsDeclaration In "Function" from "GlobalScope" line 4":
		<TYPEDEF> <SPACE> <STRUCT> <SPACE> <IDENTIFIER=s_struct> <NEWLINE>
		<LBRACE> <NEWLINE>
		<TAB> <INT> <TAB> <IDENTIFIER=smth> <SEMI_COLON> <NEWLINE>
.NORME_ERRORS.h - IsBlockEnd In "Function" from "GlobalScope" line 7":
		<RBRACE> <TAB> 
Traceback (most recent call last):
  File "/home/kostya/.local/bin/norminette", line 8, in <module>
    sys.exit(main())
  File "/home/kostya/.local/lib/python3.8/site-packages/norminette/__main__.py", line 120, in main
    registry.run(context, source)
  File "/home/kostya/.local/lib/python3.8/site-packages/norminette/registry.py", line 63, in run
    ret, jump = self.run_rules(context, rule)
  File "/home/kostya/.local/lib/python3.8/site-packages/norminette/registry.py", line 41, in run_rules
    self.run_rules(context, self.rules[r])
  File "/home/kostya/.local/lib/python3.8/site-packages/norminette/registry.py", line 30, in run_rules
    rule.run(context)
  File "/home/kostya/.local/lib/python3.8/site-packages/norminette/rules/check_global_naming.py", line 43, in run
    if context.peek_token(i).value.startswith("g_") is False and context.peek_token(i).value != "environ":
AttributeError: 'NoneType' object has no attribute 'value'
```
#
**Additional infos**
 - OS: `Linuxmint 20.2 uma`
 - python --version: `Python 3.8.10`
 - norminette -v: `norminette 3.3.40`

**Comment by N0ich** [comment]
#251 fix also fixes crash (wrong identified line)
