### ISSUE TITLE
IndexError: list index out of range when just "int" inside a file

### ISSUE THREAD

**Issue by caio-vinicius** [42school/norminette#297]
**Describe the bug**
when a file has only "int" inside it, the program returns a catastrophic error

**Erroneous code**
```
// test.c
int
```

**Additional infos**
 - OS: Ubuntu 20.04
 - python --version: 3.8.10
 - norminette -v: 3.3.51

**Additional context**

```bash
Traceback (most recent call last):
  File "/usr/local/bin/norminette", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/norminette/__main__.py", line 121, in main
    registry.run(context, source)
  File "/usr/local/lib/python3.8/dist-packages/norminette/registry.py", line 65, in run
    ret, jump = self.run_rules(context, rule)
  File "/usr/local/lib/python3.8/dist-packages/norminette/registry.py", line 27, in run_rules
    ret, read = rule.run(context)
  File "/usr/local/lib/python3.8/dist-packages/norminette/rules/is_var_declaration.py", line 179, in run
    and context.check_token(tmp - 1, ["SPACE", "TAB", "NEWLINE"]) is False
  File "/usr/local/lib/python3.8/dist-packages/norminette/context.py", line 179, in check_token
    tkn = self.peek_token(pos)
  File "/usr/local/lib/python3.8/dist-packages/norminette/context.py", line 172, in peek_token
    return self.tokens[pos] if pos < len(self.tokens) else None
IndexError: list index out of range
```

**Comment by Jkutkut** [comment]
I believe this error has already been fixed. I am not able to replicate it.

**Erroneous code**

```
// test.c
int
```

**Additional infos**
- OS: Ubuntu 22.04.1 LTS
- python --version: 3.10.4
- norminette -v: 3.3.51


**Execution example**
```
$> norminette test.c
test.c: Error!
	Error: Unrecognized line (1, 1) while parsing line [<INT>]
$>
```

**Comment by wil-pedago** [comment]
Fixed in 3.3.60. A file holding only `int` no longer ends in `IndexError`. It is reported as a parsing error alongside the other errors in the file, and the exit status is 1.
