### ISSUE TITLE
Norminette breaks when checking a header file without header pre-processor protection

### ISSUE THREAD

**Issue by vinicius507** [42School/norminette#349]
**Describe the bug**
Norminette breaks when checking the norm in a `.h` file without header protections.

**Erroneous code**
```c
/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   test.h                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: vgoncalv <vgoncalv@student.42sp.org.br>    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2022/08/17 20:54:19 by vgoncalv          #+#    #+#             */
/*   Updated: 2022/08/20 16:31:22 by vgoncalv         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#define FT_ABS(VALUE) VALUE < 0 ? VALUE * -1 : VALUE
```

**Additional infos**
 - OS: Linux 42sp 5.15.62-1-lts #1 SMP Sun, 21 Aug 2022 18:43:48 +0000 x86_64 GNU/Linux
 - python --version: Python 3.10.6
 - norminette -v: 3.3.51

**Additional context**
Executing `norminette` on `test.h`:

```sh
$ norminette -R CheckDefine test.h
Traceback (most recent call last):
  File "/home/vinicius/.local/bin/norminette", line 33, in <module>
    sys.exit(load_entry_point('norminette==3.3.51', 'console_scripts', 'norminette')())
  File "/home/vinicius/.local/lib/python3.10/site-packages/norminette/__main__.py", line 121, in main
    registry.run(context, source)
  File "/home/vinicius/.local/lib/python3.10/site-packages/norminette/registry.py", line 65, in run
    ret, jump = self.run_rules(context, rule)
  File "/home/vinicius/.local/lib/python3.10/site-packages/norminette/registry.py", line 43, in run_rules
    self.run_rules(context, self.rules[r])
  File "/home/vinicius/.local/lib/python3.10/site-packages/norminette/registry.py", line 32, in run_rules
    rule.run(context)
  File "/home/vinicius/.local/lib/python3.10/site-packages/norminette/rules/check_preprocessor_define.py", line 127, in run
    context.new_error("HEADER_PROT_ALL_2", context.peek_token(i))
  File "/home/vinicius/.local/lib/python3.10/site-packages/norminette/context.py", line 204, in new_error
    self.errors.append(NormError(errno, tkn.pos[0], tkn.pos[1]))
AttributeError: 'NoneType' object has no attribute 'pos'
```

**Comment by matthieu42Network** [comment]
fixed in 3.3.52
