### ISSUE TITLE
Norminette breaking when checking macros on headers

### ISSUE THREAD

**Issue by LucasKuhn** [42School/norminette#352]
Norminette breaks when checking macros on header

**Erroneous code**

The following header
```h
#define EVEN(x) (x % 2 == 0)
```
and running 
```bash
norminette -R CheckDefine
```
I get the following error:
```bash
Traceback (most recent call last):
  File "/usr/local/bin/norminette", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/norminette/__main__.py", line 121, in main
    registry.run(context, source)
  File "/usr/local/lib/python3.8/dist-packages/norminette/registry.py", line 65, in run
    ret, jump = self.run_rules(context, rule)
  File "/usr/local/lib/python3.8/dist-packages/norminette/registry.py", line 43, in run_rules
    self.run_rules(context, self.rules[r])
  File "/usr/local/lib/python3.8/dist-packages/norminette/registry.py", line 32, in run_rules
    rule.run(context)
  File "/usr/local/lib/python3.8/dist-packages/norminette/rules/check_preprocessor_define.py", line 127, in run
    context.new_error("HEADER_PROT_ALL_2", context.peek_token(i))
  File "/usr/local/lib/python3.8/dist-packages/norminette/context.py", line 204, in new_error
    self.errors.append(NormError(errno, tkn.pos[0], tkn.pos[1]))
AttributeError: 'NoneType' object has no attribute 'pos'
```
Should this be the case?

**Additional infos**
 - OS: Ubuntu 20.04.5 LTS
 - python --version: 3.8.10
 - norminette -v: 3.3.51

**Additional context**

**Comment by matthieu42Network** [comment]
fixed in 3.3.52
