### ISSUE TITLE
norminette -R CheckDefine crash on a header.h file

### ISSUE THREAD

**Issue by maitreverge** [42School/norminette#379]
**Describe the bug**
I am trying to run norminette -R CheckDefine on the following code :

**Erroneous code**
``` c
/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ft_boolean.h                                       :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: fverge <fverge@student.42.fr>              +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/06/04 20:47:56 by fverge            #+#    #+#             */
/*   Updated: 2023/06/04 20:48:06 by fverge           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef __FT_BOOLEAN_H__
#define __FT_BOOLEAN_H__
#include <unistd.h>
typedef enum bool
{
	true,
	false,

}	t_bool;
#define TRUE true
#define FALSE false
#define EVEN(x) (x % 2 == 0)
#define EVEN_MSG "I have an even number of arguments."
#define ODD_MSG "I have an odd number of arguments."
#define SUCCESS 0
#endif
```

**Norminette Error Message Output**

`norminette -R CheckDefine ft_boolean.h`

``` bash
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/norminette", line 33, in <module>
    sys.exit(load_entry_point('norminette==3.3.51', 'console_scripts', 'norminette')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/norminette/__main__.py", line 121, in main
    registry.run(context, source)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/norminette/registry.py", line 65, in run
    ret, jump = self.run_rules(context, rule)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/norminette/registry.py", line 43, in run_rules
    self.run_rules(context, self.rules[r])
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/norminette/registry.py", line 32, in run_rules
    rule.run(context)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/norminette/rules/check_preprocessor_define.py", line 127, in run
    context.new_error("HEADER_PROT_ALL_2", context.peek_token(i))
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/norminette/context.py", line 204, in new_error
    self.errors.append(NormError(errno, tkn.pos[0], tkn.pos[1]))
                                        ^^^^^^^
AttributeError: 'NoneType' object has no attribute 'pos'

```
**Additional infos**
 - OS: macOS 12.6.3
 - python --version: 3.11.0
 - norminette -v: 3.3.51

**Additional context**
This error looks similar to #352, so my apologies if it's a duplicate.

**Comment by matthieu42Network** [comment]
fixed in 3.3.52
