### ISSUE TITLE
having trouble executing norminette 

### ISSUE THREAD

**Issue by sungyongcho** [42School/norminette#41]
hello,

I'm having trouble executing norminette on my personal mac.

after installing with command `python3 setup.py install`,

I am getting this error everywhere where I try executing norminette.

```
Traceback (most recent call last):
  File "/usr/local/bin/norminette", line 11, in <module>
    load_entry_point('norminette==3.0.4', 'console_scripts', 'norminette')()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen zipimport>", line 259, in load_module
  File "/Library/Python/3.8/site-packages/norminette-3.0.4-py3.8.egg/norminette/__main__.py", line 10, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/Library/Python/3.8/site-packages/norminette-3.0.4-py3.8.egg/norminette/registry.py", line 2, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/Library/Python/3.8/site-packages/norminette-3.0.4-py3.8.egg/norminette/context.py", line 3, in <module>
ModuleNotFoundError: No module named 'tools.colors'
```

Here are more details of my local environment:

![image](https://user-images.githubusercontent.com/46742040/107771469-26407f00-6d7e-11eb-8cae-b3d8b8a46405.png)

![image](https://user-images.githubusercontent.com/46742040/107771716-80d9db00-6d7e-11eb-9c12-bbabf39b7edc.png)

![image](https://user-images.githubusercontent.com/46742040/107771560-44a67a80-6d7e-11eb-9ece-ee3f11a4425b.png)

As many of you see, I'm pretty much new to programming world, so please let me know what I'll need to do to fix the problem. Thanks!

**Comment by sungyongcho** [comment]
hello, i have no idea what i've done to my computer, but after couple days, norminette works like a charm. thanks for the concern, and i'm going to close this issue as well.
