### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'pos'

### ISSUE THREAD

**Issue by tdanielsousa** [42school/norminette#518]
**Describe the bug**
I had a space after the function name before the argument so : function_name (int n), and i had a main commented after the function.
It gave the error that i pasted down below and no more info.
Removing the main fixed this issue, although there was no problem with the main, and that said main was inside /*  */ .  
I then fixed the function name to function_name(int n) removing the space and the error was gone, even with the same main in place, that single space cause norminette to not work.

**Erroneous code**

Traceback (most recent call last):
  File "/home/tiago/.local/bin/norminette", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/tiago/.local/share/pipx/venvs/norminette/lib/python3.12/site-packages/norminette/__main__.py", line 155, in main
    registry.run(context, source)
  File "/home/tiago/.local/share/pipx/venvs/norminette/lib/python3.12/site-packages/norminette/registry.py", line 61, in run
    ret, jump = self.run_rules(context, rule)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiago/.local/share/pipx/venvs/norminette/lib/python3.12/site-packages/norminette/registry.py", line 37, in run_rules
    self.run_rules(context, rule)
  File "/home/tiago/.local/share/pipx/venvs/norminette/lib/python3.12/site-packages/norminette/registry.py", line 29, in run_rules
    result = rule.run(context)
             ^^^^^^^^^^^^^^^^^
  File "/home/tiago/.local/share/pipx/venvs/norminette/lib/python3.12/site-packages/norminette/rules/check_func_declaration.py", line 66, in run
    context.new_error("NO_SPC_BFR_PAR", context.peek_token(i))
  File "/home/tiago/.local/share/pipx/venvs/norminette/lib/python3.12/site-packages/norminette/context.py", line 249, in new_error
    pos = tkn.pos
          ^^^^^^^
AttributeError: 'NoneType' object has no attribute 'pos'

**Comment by wil-pedago** [comment]
Correction to my earlier comment: #595 is listed as Refs for this one, not Closes.

The traceback in the report points at `check_func_declaration`, and that call site is still unguarded. I have no input that reaches it.

What the branch fixes is the same failure at a different call site, in `CheckSpacing`, reproduced with a file whose last line holds a single space. So the class of crash is addressed and this particular one may well be too, but I cannot confirm it against the report.
