### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'type'

### ISSUE THREAD

**Issue by baschni** [42school/norminette#522]
Running norminette on a .h file with one line content
```
int a(int b)
```

yields the following error:
```
Traceback (most recent call last):
  File "/home/baschnit/.local/bin/norminette", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/baschnit/.local/pipx/venvs/norminette/lib/python3.11/site-packages/norminette/__main__.py", line 155, in main
    registry.run(context, source)
  File "/home/baschnit/.local/pipx/venvs/norminette/lib/python3.11/site-packages/norminette/registry.py", line 61, in run
    ret, jump = self.run_rules(context, rule)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/baschnit/.local/pipx/venvs/norminette/lib/python3.11/site-packages/norminette/registry.py", line 29, in run_rules
    result = rule.run(context)
             ^^^^^^^^^^^^^^^^^
  File "/home/baschnit/.local/pipx/venvs/norminette/lib/python3.11/site-packages/norminette/rules/is_func_prototype.py", line 200, in run
    ret, read = self.check_func_format(context)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/baschnit/.local/pipx/venvs/norminette/lib/python3.11/site-packages/norminette/rules/is_func_prototype.py", line 181, in check_func_format
    i = context.skip_nest(i)
        ^^^^^^^^^^^^^^^^^^^^
  File "/home/baschnit/.local/pipx/venvs/norminette/lib/python3.11/site-packages/norminette/context.py", line 370, in skip_nest
    c = self.peek_token(pos).type
        ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'type'
```

using norminette 3.3.55

**Comment by otto-mata** [comment]
Hello !
This comes from a regression introduced in march 2022 (see #256 )
Strangely, commenting out a `try except` block wasn't the proper solution.
Reverting this change correctly exits the norminette, although it should be noted that additional informations are necessary, as `Error: Code ended unexpectedly.` is not quite descriptive enough.

Best,
tblochet

**Comment by wil-pedago** [comment]
Fixed in #595. `int a(int b)` in a `.h` file gave the traceback above because `skip_nest` had its end of file guard commented out. It now raises a parsing error, which is reported like any other error:

```
i522.h: Error!
Error: PARSING_ERROR        	Error: Unexpected EOF line 8
```

This was one of five crash sites. On a corpus of 618 truncated copies of the existing test samples, 131 ended in a traceback before, none do now.
