### ISSUE TITLE
Norminette crashes in a return statement

### ISSUE THREAD

**Issue by lightdiscord** [42School/norminette#84]
**Describe the bug**

The norminette crashes when a closing parentheses is on its own line in a return statement.

**Erroneous code**

```c
int f(void)
{
    return (g()
    );
}
```

**Additional infos**
 - OS: NixOS 21.03
 - python --version: 3.9.0a2
 - norminette -v: 3.1.3

**Additional context**

<details>
  <summary>Traceback</summary>
  
```console
$ norminette -dd
lol.c - IsFuncDeclaration In "GlobalScope" from "None" line 1":
                <INT> <SPACE> <IDENTIFIER=f> <LPARENTHESIS> <VOID> <RPARENTHESIS> <NEWLINE>
lol.c - IsBlockStart In "Function" from "GlobalScope" line 2":
                <LBRACE> <NEWLINE>
Traceback (most recent call last):
  File "/nix/store/r23zg32ay9cy50z63n1n0ap4mm2qfv5m-norminette-3.1.3/bin/.norminette-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/r23zg32ay9cy50z63n1n0ap4mm2qfv5m-norminette-3.1.3/lib/python3.8/site-packages/norminette/__main__.py", line 87, in main
    registry.run(context, source)
  File "/nix/store/r23zg32ay9cy50z63n1n0ap4mm2qfv5m-norminette-3.1.3/lib/python3.8/site-packages/norminette/registry.py", line 60, in run
    ret, jump = self.run_rules(context, rule)
  File "/nix/store/r23zg32ay9cy50z63n1n0ap4mm2qfv5m-norminette-3.1.3/lib/python3.8/site-packages/norminette/registry.py", line 38, in run_rules
    self.run_rules(context, self.rules[r])
  File "/nix/store/r23zg32ay9cy50z63n1n0ap4mm2qfv5m-norminette-3.1.3/lib/python3.8/site-packages/norminette/registry.py", line 27, in run_rules
    rule.run(context)
  File "/nix/store/r23zg32ay9cy50z63n1n0ap4mm2qfv5m-norminette-3.1.3/lib/python3.8/site-packages/norminette/rules/check_nest_line_indent.py", line 86, in run
    self.find_nest_content(context, nest, i)
  File "/nix/store/r23zg32ay9cy50z63n1n0ap4mm2qfv5m-norminette-3.1.3/lib/python3.8/site-packages/norminette/rules/check_nest_line_indent.py", line 64, in find_nest_content
    context.new_error("TOO_FEW_TAB", context.peek_token(i))
  File "/nix/store/r23zg32ay9cy50z63n1n0ap4mm2qfv5m-norminette-3.1.3/lib/python3.8/site-packages/norminette/context.py", line 190, in new_error
    self.errors.append(NormError(errno, tkn.pos[0], tkn.pos[1]))
AttributeError: 'NoneType' object has no attribute 'pos'
```
  
</details>

**Comment by N0ich** [comment]
Hello,
I can't seem to reproduce it when running it in my own environment. Can you add the result of `norminette -dd file.c` to the traceback?

**Comment by lightdiscord** [comment]
Done!

**Comment by N0ich** [comment]
Can you contact me on the schools slack? @noich
Thanks!
